kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sample-database
  namespace: fiap-aso6-g27-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
