kind: Secret
apiVersion: v1
metadata:
  name: sample-database
  namespace: fiap-aso6-g27-test
data:
  database-name: c2FtcGxlZGI=
  database-password: c2FtcGxlZGI=
  database-user: c2FtcGxlZGI=
type: Opaque
